[project]
name = "audiobook-from-pdf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gtts>=2.5.4",
    "pymupdf>=1.25.5",
    "pypdf2>=3.0.1",
    "pyttsx3>=2.98",
]
